services:

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-api:
    build: ./python-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8082:8000"

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - python-api
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "8081:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm build && pnpm start

volumes:
  pgdata:
