services:

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  detection-api:
    image: ghcr.io/bachelor-group-13/detection-api:latest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8082:8000"

  backend:
    image: ghcr.io/bachelor-group-13/backend:latest
    env_file:
      - .env
    depends_on:
      - db
      - detection-api
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/bachelor-group-13/frontend:latest
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "8081:3000"
    restart: unless-stopped

volumes:
  pgdata:
