name: Deploy to VM

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment-orchestrator repo
        uses: actions/checkout@v3

      - name: Add VM host to known_hosts
        run: ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy with docker-compose
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/app
            echo "Pulling latest images from GHCR..."
            docker-compose --env-file .env pull
            echo "Starting services..."
            docker-compose --env-file .env up -d
            echo "Deployment complete."
          EOF
