name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Which service to deploy (frontend, backend, detection-api, or all)'
        required: true
        default: 'all'

  workflow_run:
    workflows:
      - "Build and Push Frontend to GHCR"
      - "Build and Push Backend to GHCR"
      - "Build and Push Detection API to GHCR"
    types: [ completed ]
 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into VM, deploy & clean up
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/inneparkert-deployment

            SERVICE="${{ github.event.inputs.service }}"
            SERVICE=${SERVICE:-all}

            if [ "$SERVICE" = "all" ]; then
              docker compose --env-file .env pull
              docker compose --env-file .env up -d --remove-orphans
            else
              docker compose --env-file .env pull "$SERVICE"
              docker compose --env-file .env up -d --no-deps "$SERVICE"
            fi

            docker image prune -a -f
            docker volume prune -f
          EOF
  
