name: Deploy to VM

on:
  workflow_run:
    workflows:
      - "Build and Push Frontend to GHCR"
      - "Build and Push Backend to GHCR"
      - "Build and Push Detection API to GHCR"
    types: [ completed ]
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into VM and deploy
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/inneparkert-deployment
            docker compose --env-file .env pull
            docker compose --env-file .env up -d
          EOF
